# Generated by Django 4.2.16 on 2024-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("orderId", models.BigIntegerField()),
                ("side", models.CharField(max_length=10)),
                ("price", models.TextField()),
                ("qty", models.TextField()),
                ("realizedPnl", models.TextField()),
                ("marginAsset", models.TextField()),
                ("quoteQty", models.TextField()),
                ("commission", models.TextField()),
                ("commissionAsset", models.TextField()),
                ("time", models.DateTimeField()),
                ("positionSide", models.TextField()),
                ("buyer", models.BooleanField()),
                ("maker", models.BooleanField()),
            ],
            options={
                "db_table": "account",
            },
        )
    ]